{{- if .Values.sharedResources.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    {{- include "ai-testops.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
{{- end }}
