{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: django-app-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.djangoApp.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.consumer.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: django-app-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: consumer-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: django-app-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: django-app-role
subjects:
- kind: ServiceAccount
  name: django-app-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consumer-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consumer-role
subjects:
- kind: ServiceAccount
  name: consumer-sa
  namespace: {{ .Values.namespace }}
{{- end }}
