apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.0.7
appVersion: "85820a5"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
