apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
