apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.0.13
appVersion: "8b58979"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
