apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.0.5
appVersion: "3b98f19"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
