apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.0.12
appVersion: "b23edee"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
