apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.3
appVersion: "96866e2"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
