apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.0.9
appVersion: "4922536"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
