apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.4
appVersion: "187316a"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
