apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.7
appVersion: "a807590"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
