apiVersion: v2
name: testops-infra
description: Infrastructure components for TestOps platform (PostgreSQL, Kafka, shared resources)
type: application
version: 1.0.5
appVersion: "1.0.0"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
