apiVersion: v2
name: testops-infra
description: Infrastructure components for TestOps platform (PostgreSQL, Kafka, shared resources)
type: application
version: 1.2.18
appVersion: "1.0.0"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com

dependencies:
  - name: postgres
    version: "1.0.0"
    condition: postgres.enabled
  - name: kafka
    version: "1.0.0"
    condition: kafka.enabled
  - name: shared
    version: "1.0.0"
  - name: prometheus
    version: "1.0.0"
    condition: prometheus.enabled
