apiVersion: v2
name: testops-publisher
description: Publisher service for TestOps platform
type: application
version: 1.4.8
appVersion: "2afe793"
keywords:
  - ai
  - testing
  - kafka
  - microservices
  - keda
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
annotations:
  "keda.sh/required": "true"
  "keda.sh/installation": |
    Install KEDA before deploying this chart:
    kubectl apply --server-side -f https://github.com/kedacore/keda/releases/download/v2.12.0/keda-2.12.0.yaml
