apiVersion: v2
name: testops-postdeploy
description: Post-deployment resources for TestOps (NetworkPolicies, Monitoring)
type: application
version: 1.0.5
appVersion: "1.0.0"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
