{{- if .Values.global.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: django-app-sa
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.djangoApp.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: django-app-role
  namespace: {{ .Values.global.namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: django-app-rolebinding
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: django-app-role
subjects:
- kind: ServiceAccount
  name: django-app-sa
  namespace: {{ .Values.global.namespace }}
{{- end }}
